### ISSUE TITLE
"promptClear" method seem not work yet in Android

### ISSUE THREAD

**Issue by bau720123** [michael79bxl/cordova-plugin-pindialog#2]
hi @michael79bxl 
I am using PGB (build.phonegap.com) 5.1.1 with your latest plugin version from npm
https://www.npmjs.com/package/cordova-plugin-pindialog

according to this
https://github.com/michael79bxl/cordova-plugin-pindialog/blob/master/src/android/PinDialog.java
it seem you have set a "promptClear" method (although I don't know what is it)
although it also have no related detail in the readme
https://github.com/michael79bxl/cordova-plugin-pindialog
and...
```
window.plugins.pinDialog.promptClear("message", callback, "title", ["OK","Cancel"]);
```
not work too
so..."promptClear" method seem not work yet in Android，right ?

**Comment by michael79bxl** [comment]
README updated. It works on android, tested.

**Comment by bau720123** [comment]
hi @michael79bxl 
yes!! for now the "promptClear" work for my android too
but..
although you said that "promptClear" have "no password field"
https://github.com/michael79bxl/cordova-plugin-pindialog/issues/2#event-413020856

but in fact，"prompt" = "promptClear"
no different (I try many times)

**Comment by michael79bxl** [comment]
There is a visual difference. With prompt, the input is hidden, with promptClear, the input is visible (not suitable for password). The same java function is called but the Cordova argument is used to use a text field instead of a password field.

```
promptInput.setInputType(InputType.TYPE_CLASS_NUMBER);
if(action.equals("prompt")) promptInput.setTransformationMethod(PasswordTransformationMethod.getInstance());
```

**Comment by michael79bxl** [comment]
NB: code updated for iOS support

**Comment by bau720123** [comment]
got it
fully understand
thanks

hope the npm version have a update too
https://www.npmjs.com/package/cordova-plugin-pindialog

**Comment by michael79bxl** [comment]
Done.

**Comment by bau720123** [comment]
thanks @michael79bxl 
really good job
