### ISSUE TITLE
"promptClear" method seem not work in iOS for now

### ISSUE THREAD

**Issue by bau720123** [michael79bxl/cordova-plugin-pindialog#3]
according to this
https://github.com/michael79bxl/cordova-plugin-pindialog/issues/2
android is work perfect finally

but I am using your new version 0.2.3 for now
https://www.npmjs.com/package/cordova-plugin-pindialog
it become iOS 9.2 not work

**Comment by michael79bxl** [comment]
Could you be more specific about what does not work.
Do you an output/error log?

**Comment by bau720123** [comment]
hi @michael79bxl 
thanks your reply
not work = no any response or trigger
I will use Xcode or some tool to check the log and feedaback to you

**Comment by bau720123** [comment]
hi @michael79bxl 

when I use this 0.2.3 version
https://www.npmjs.com/package/cordova-plugin-pindialog
it will have the "promptClear" problem in iOS

but when I use this 0.2.4 version
https://www.npmjs.com/package/cordova-plugin-pindialog-fork
problem solved

could I ask...
it look like both of them are created by you
what the difference ?
if one day have a new version，which one is the master ?

**Comment by michael79bxl** [comment]
FYI README updated ;-)
